function [fitresult, gof] = findoffsetfit(x_pos, y_pos, spot_pos, datafilename, fitname, endframe)
%CREATEFIT(X_POS,Y_POS,spot_pos)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x_pos
%      Y Input : y_pos
%      Z Output: spot_pos
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Feb-2017 17:50:47


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x_pos, y_pos, spot_pos );

% Set up fittype and options.
ft = fittype( 'poly11' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

figure_title = strcat(datafilename,'_',num2str(endframe),'_',fitname);

% Plot fit with data.
f = figure( 'Name', figure_title );
h = plot(fitresult, [xData, yData], zData );
legend(h,figure_title,'spot_pos vs. x_pos, y_pos', 'Location', 'NorthEast' );
% Label axes
xlabel x_pos
ylabel y_pos
zlabel spot_pos
grid on
view( -0.5, 14.4 );

mkdir(strcat('../res/fit_graph/',datafilename,'_',num2str(endframe)));
saveas(f,strcat('../res/fit_graph/',datafilename,'_',num2str(endframe),'/',figure_title,'.png'));


